name: Publish
on:
  push:
    tags:
      - 'version/*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: '25'

      - name: Prepare Gradle Wrapper
        run: chmod +x ./gradlew

      - uses: gradle/actions/setup-gradle@v4

      - name: Release
        run: ./gradlew publishMod -PCURSEFORGE_TOKEN=${{ secrets.CF_TOKEN }} -PMODRINTH_TOKEN=${{ secrets.MODRINTH_TOKEN }} --no-configuration-cache

      - uses: Toma1O6/file-read-action@v1
        id: changelog
        with:
          file: 'CHANGELOG.md'
          max-chars: '4096'

      - uses: T-T-Team/discord-release-announcement-action@v1.0.1
        with:
          webhookUrl: ${{ secrets.WEBHOOK_URL }}
          message: '<@&1050082657511411763>'
          title: 'Collectors Album'
          homepage: 'https://github.com/T-T-Team/CollectorsAlbum'
          changelog: ${{ steps.changelog.outputs.content }}
          color: '9576191'
          iconUrl: 'https://media.forgecdn.net/avatars/589/367/637960226211119035.png'
          note: 'CurseForge file may take up to 1 hour to be published'
          curseForgeUrl: 'https://www.curseforge.com/minecraft/mc-mods/collectors-album'
          modrinthUrl: 'https://modrinth.com/mod/collectors-album'
          sourcesUrl: 'https://github.com/T-T-Team/CollectorsAlbum'
          issueTrackerUrl: 'https://github.com/T-T-Team/CollectorsAlbum/issues'
          wikiUrl: 'https://github.com/T-T-Team/CollectorsAlbum/wiki'
          donationUrl: 'https://www.patreon.com/c/tnt_team'